# Generated by Django 2.1.7 on 2019-04-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_playername_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStableford',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerstableford1', models.IntegerField(blank=True, null=True)),
                ('playerstableford2', models.IntegerField(blank=True, null=True)),
                ('playerstableford3', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
